apiVersion: v1
kind: Service
metadata:
  name: green-eks
  labels:
    app: green-eks
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: green-eks
    protocol: TCP
  - name: "443"
    port: 443
    targetPort: green-eks
    protocol: TCP
  selector:
    app: green-eks
    type: LoadBalancer

apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-eks
  labels:
    app: green-eks
spec:
  replicas: 1
  selector:
      matchLabels:
        app: green-eks
  template:
    metadata:
      labels:
        app: green-eks
    spec:
      containers:
      - name: green-eks
        image: 170529709485.dkr.ecr.ap-south-1.amazonaws.com/greens-ci-cd-eks:latest
        ports:
          - containerPort: 9000
            name: green-eks
            protocol: TCP
        
